In [10]:
import numpy as np

In [11]:
X = np.array([[0, 0],[0, 1],[1, 0],[1, 1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [19]:
def sig(x) :
    return (1+np.exp(-x))**-1
def derivative_sig(x) :
    return sig(x) * (1 - sig(x))

In [13]:
weights = np.random.random([2, 1]) * 2 -1
weights

array([[-0.85153482],
       [-0.89039966]])

In [14]:
bias = np.random.random([1]) * 2 -1
bias

array([ 0.04792273])

In [16]:
out0 = X
output = sig(np.dot(out0, weights) + bias)
output

array([[ 0.51197839],
       [ 0.30101337],
       [ 0.30925339],
       [ 0.15524898]])

In [17]:
wh = np.random.random([2, 2]) * 2 - 1
bh = np.random.random([1, 2]) * 2 - 1
wo = np.random.random([2, 1]) * 2 - 1
bo = np.random.random([1, 1]) * 2 - 1

In [18]:
out0 = X
output_hidden = sig(np.dot(out0, wh) + bh)
output = sig(np.dot(output_hidden, wo) + bo)
out0, output_hidden, output

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]), array([[ 0.64673647,  0.50891222],
        [ 0.45736311,  0.56217483],
        [ 0.64728736,  0.44251135],
        [ 0.4579618 ,  0.49584121]]), array([[ 0.47214224],
        [ 0.47793214],
        [ 0.46436415],
        [ 0.47015162]]))