In [46]:
import numpy as np

In [47]:
X = np.array([[0, 0],[0, 1],[1, 0],[1, 1]])
Y = np.array([[0, 1, 1, 0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [48]:
X, Y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]), array([[0],
        [1],
        [1],
        [0]]))

In [49]:
def sig(x) :
    return (1+np.exp(-x))**-1
def derivative_sig(x) :
    return sig(x) * (1 - sig(x))

In [50]:
wh = np.random.random([2, 2]) * 2 - 1
bh = np.random.random([1, 2]) * 2 - 1
wo = np.random.random([2, 1]) * 2 - 1
bo = np.random.random([1, 1]) * 2 - 1

wh, bh, wo, bo

(array([[ 0.74349802,  0.63242146],
        [-0.78827955, -0.21417909]]),
 array([[ 0.23570769, -0.62037378]]),
 array([[ 0.18117764],
        [ 0.84216529]]),
 array([[-0.94728912]]))

In [56]:
lr = 10

for iter in range(10000):
    out0 = X
    inputHidden = np.dot(out0, wh) +bh
    output_hidden = sig(inputHidden)
    
    inputForOutLayer = np.dot(output_hidden, wo) + bo 
    output = sig(inputForOutLayer)

    first_term_out_layer = output - Y
    second_term_out_layer = derivative_sig(inputForOutLayer)
    first_two_out_layer = first_term_out_layer * second_term_out_layer

    first_term_hidden_layer = np.dot(first_two_out_layer, wo.T)
    second_term_hidden_layer = derivative_sig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    changes_output = np.dot(output_hidden.T, first_two_out_layer)
    changes_output_bias = np.sum(first_two_out_layer, keepdims=True, axis = 0)

    changes_hidden = np.dot(out0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, keepdims=True, axis = 0)

    wo -= lr * changes_output 
    bo -= lr * changes_output_bias

    wh -= lr * changes_hidden
    bh -= lr * changes_hidden_bias

out0 = X
inputHidden = np.dot(out0, wh) +bh
output_hidden = sig(inputHidden)
inputForOutLayer = np.dot(output_hidden, wo) + bo 
output = sig(inputForOutLayer)

output, wh, bh, wo, bo

(array([[ 0.00312357],
        [ 0.99640627],
        [ 0.99704214],
        [ 0.00280565]]), array([[ 7.10824318,  6.88874196],
        [-6.90971619, -7.03105518]]), array([[ 3.46080584, -3.67461316]]), array([[-12.47006368],
        [ 12.77488699]]), array([[ 6.00877263]]))