In [61]:
import numpy as np

In [62]:
def cost(result,m,train):
    c=0
    for i in range(len(train)):
        c+= (result[i][0]-(m*train[i]).sum())**2
    return c/len(train)

In [96]:
def fit(train_x,train_y,alpha,itr):
    m=np.array([np.random.rand() for i in range(len(train_x[0]))])
    for i in range(itr):
        slope=np.array([0 for i in range(len(train_x[0]))])
        for j in range(len(train_x)):
            for k in range(len(train_x[0])):
                slope[k]+=(-2*train_x[j][k]/(len(train_x)))*(train_y[j][0]-(m*train_x[j]).sum())
        m=m-alpha*slope
        print("cost",i+1,":",cost(train_y,m,train_x),"    ",m)
    return m          
    

In [123]:
def predict(inp,m):
    result=np.array([0.0 for i in range(len(inp))])
    result=result.reshape(len(result),1)
    #m=m.reshape(-1, len(m))
    print("x, m", inp.shape, m.shape)
    print("x[0], m", inp[0].shape, m.shape)
    print(inp[0], m)
    print(inp[0]*m)
    for i in range(len(inp)):
        result[i][0]=(inp[i]*m).sum()
    return result

In [64]:
train_data=np.loadtxt('training_ccpp_x_y_train.csv',delimiter=',')
train_x=train_data[:,0:len(train_data[0])-1]
train_y=train_data[:,len(train_data[0])-1:len(train_data[0])]
test_data=np.loadtxt('test_ccpp_x_test.csv',delimiter=',')
test_x=test_data
ap=np.array([1 for i in range(len(test_x))])
ap=ap.reshape(len(test_x),1)
test_x= np.append(test_x,ap,axis=1)

ap=np.array([1 for i in range(len(train_x))])
ap=ap.reshape(len(train_x),1)
train_x= np.append(train_x,ap,axis=1)


In [85]:
def manager():
    train_x,train_y,test_x=loadAndShape()
    alpha=1e-7
    itr=100
    m=fit(train_x,train_y,alpha,itr)
    finalResult=predict(test_x,m)
   # print(finalResult.shape)
    np.savetxt("prediction_power.csv", finalResult, delimiter=",")   
    return 


In [86]:
manager()

cost 1 : 130411.4665648611      [0.0013952 0.0045471 0.0917466 0.006319  0.       ]
cost 2 : 82325.72804552907      [0.0024317 0.0080692 0.1644992 0.0112663 0.       ]
cost 3 : 52043.85999811879      [0.0031653 0.010783  0.2221976 0.0151233 0.       ]
cost 4 : 32967.08808733392      [0.0036487 0.0128066 0.2679585 0.0181209 0.       ]
cost 5 : 20940.67947681674      [0.0040132 0.0144539 0.3042512 0.0204336 0.       ]
cost 6 : 13356.051943410119      [0.0041145 0.0155737 0.3330426 0.0222035 0.       ]
cost 7 : 8569.454934810865      [0.0041147 0.0163444 0.3558762 0.0235456 0.       ]
cost 8 : 5542.419340441883      [0.0041147 0.0170581 0.3739946 0.0245365 0.       ]
cost 9 : 3627.2827477895357      [0.0041147 0.017531  0.388369  0.025271  0.       ]
cost 10 : 2414.99689333468      [0.0041147 0.0175713 0.3997763 0.0257536 0.       ]
cost 11 : 1644.5804556577036      [0.0041147 0.0175719 0.408833  0.0260625 0.       ]
cost 12 : 1153.2976223069293      [0.0041147 0.0175721 0.4160276 0.02628

cost 98 : 257.1825524744314      [0.0041147 0.0175721 0.444298  0.0265364 0.       ]
cost 99 : 257.17755606960594      [0.0041147 0.0175721 0.4442999 0.0265364 0.       ]
cost 100 : 257.17282947152756      [0.0041147 0.0175721 0.4443017 0.0265364 0.       ]


In [92]:
from sklearn.metrics import mean_squared_error 

In [124]:
preds = predict(train_x, m)
mean_squared_error(y_true=train_y, y_pred=preds)


x, m (7176, 5) (5,)
x[0], m (5,) (5,)
[8.58000e+00 3.83800e+01 1.02103e+03 8.43700e+01 1.00000e+00] [0.0001377  0.00045069 0.009081   0.00062535 0.        ]
[1.18146343e-03 1.72976703e-02 9.27197374e+00 5.27605095e-02
 0.00000000e+00]


198457.3003676227

In [125]:
preds

array([[9.34321338],
       [9.30825088],
       [9.25947748],
       ...,
       [9.24183805],
       [9.31043114],
       [9.24017508]])

In [121]:
a = np.array([8.58000e+00, 3.83800e+01, 1.02103e+03, 8.43700e+01, 1.00000e+00]) 
b = np.array([0.0001377,  0.00045069, 0.009081,   0.00062535, 0. ])
a*b

array([1.18146600e-03, 1.72974822e-02, 9.27197343e+00, 5.27607795e-02,
       0.00000000e+00])

In [122]:
(a*b).sum()

9.343213157700001